apiVersion: v2
description: A Helm chart for the HMCTS CCD product.
name: ccd
# Static chart version, as uses tag
version: 0.1.0 # Do not change
icon: https://github.com/hmcts/chart-ccd/raw/master/images/icons8-java-50.png
keywords:
  - ccd
  - core-case-data
  - cdm
  - case-data-management
dependencies:
  - name: postgresql
    version: 10.16.2
    repository: https://charts.bitnami.com/bitnami
    condition: ccd.postgresql.enabled

  - name: rpe-service-auth-provider
    version: 0.3.79
    repository: '@hmctspublic'
    condition: ccd.s2s.enabled

  - name: ccd-user-profile-api
    version: 1.6.3
    repository: '@hmctspublic'
    condition: ccd.userProfile.enabled

  - name: ccd-definition-store-api
    version: 1.6.5
    repository: '@hmctspublic'
    condition: ccd.definitionStore.enabled

  - name: ccd-data-store-api
    version: 2.0.2
    repository: '@hmctspublic'
    condition: ccd.dataStore.enabled

  - name: ccd-api-gateway-web
    version: 1.2.1
    repository: '@hmctspublic'
    condition: ccd.apiGatewayWeb.enabled

  - name: ccd-admin-web
    version: 2.2.1
    repository: '@hmctspublic'
    condition: ccd.adminWeb.enabled

  - name: draft-store-service
    version: 2.0.25
    repository: '@hmctspublic'
    condition: ccd.draftStore.enabled

  - name: dm-store
    version: 2.1.31
    repository: '@hmctspublic'
    condition: ccd.dmStore.enabled

  - name: ccd-case-print-service
    version: 1.3.1
    repository: '@hmctspublic'
    condition: ccd.printService.enabled

  - name: ccd-case-activity-api
    version: 1.3.4
    repository: '@hmctspublic'
    condition: ccd.activityApi.enabled

  - name: ccd-test-stubs-service
    version: 1.2.3
    repository: '@hmctspublic'
    condition: ccd.testStubsService.enabled

  - name: ccd-definition-importer
    version: 1.3.1
    repository: '@hmctspublic'
    condition: ccd.definitionImporter.enabled

  - name: ccd-user-profile-importer
    version: 1.2.2
    repository: '@hmctspublic'
    condition: ccd.userProfileImporter.enabled

  - name: blobstorage
    version: 0.2.1
    repository: '@hmctspublic'
    condition: ccd.blobstorage.enabled

  - name: em-anno
    version: 1.0.10
    repository: '@hmctspublic'
    condition: ccd.emAnnotation.enabled

  - name: elasticsearch
    version: 7.8.1
    repository: '@hmctspublic'
    condition: ccd.elastic.enabled

  - name: logstash
    version: 2.4.1
    repository: '@hmctspublic'
    condition: ccd.elastic.enabled

  - name: am-role-assignment-service
    version: 0.0.60
    repository: '@hmctspublic'
    condition: ccd.ras.enabled
