apiVersion: v1
description: A Helm chart for the HMCTS CCD product.
name: ccd
# This is the chart version. This doesn't need to be incremented on every change.
# It is managed by release pipeline based on Github tag
version: 4.2.2
icon: https://github.com/hmcts/chart-ccd/raw/master/images/icons8-java-50.png
keywords:
  - ccd
  - core-case-data
  - cdm
  - case-data-management
