apiVersion: v2
description: A Helm chart for the HMCTS CCD product.
name: ccd
# Static chart version, as uses tag
version: 0.1.1
icon: https://github.com/hmcts/chart-ccd/raw/master/images/icons8-java-50.png
keywords:
  - ccd
  - core-case-data
  - cdm
  - case-data-management
dependencies:
  - name: rpe-service-auth-provider
    version: 0.3.112
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: ccd.s2s.enabled

  - name: ccd-user-profile-api
    version: 1.6.15
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: ccd.userProfile.enabled

  - name: ccd-definition-store-api
    version: 1.6.17
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: ccd.definitionStore.enabled

  - name: ccd-data-store-api
    version: 2.0.28
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: ccd.dataStore.enabled

  - name: ccd-api-gateway-web
    version: 1.2.7
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: ccd.apiGatewayWeb.enabled

  - name: ccd-admin-web
    version: 2.2.8
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: ccd.adminWeb.enabled

  - name: draft-store-service
    version: 2.2.5
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: ccd.draftStore.enabled

  - name: dm-store
    version: 2.2.22
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: ccd.dmStore.enabled

  - name: ccd-case-print-service
    version: 1.3.7
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: ccd.printService.enabled

  - name: ccd-case-activity-api
    version: 1.3.9
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: ccd.activityApi.enabled

  - name: ccd-test-stubs-service
    version: 1.2.12
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: ccd.testStubsService.enabled

  - name: ccd-definition-importer
    version: 1.3.3
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: ccd.definitionImporter.enabled

  - name: ccd-user-profile-importer
    version: 1.2.2
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: ccd.userProfileImporter.enabled

  - name: blobstorage
    version: 0.3.0
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: ccd.blobstorage.enabled

  - name: em-anno
    version: 2.0.22
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: ccd.emAnnotation.enabled

  - name: elasticsearch
    version: 7.17.3
    repository: 'https://helm.elastic.co'
    condition: ccd.elastic.enabled

  - name: logstash
    version: 8.5.1
    repository: 'https://helm.elastic.co'
    condition: ccd.elastic.enabled

  - name: am-role-assignment-service
    version: 0.0.79
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: ccd.ras.enabled
  
  - name: ccd-message-publisher
    version: 0.1.17
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: ccd.mps.enabled
  
  - name: postgresql
    version: 1.0.2
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: postgresql.enabled
