apiVersion: v1
description: A Helm chart for the HMCTS CCD product
name: ccd
version: 4.0.6-alpha
icon: https://github.com/hmcts/chart-ccd/raw/master/images/icons8-java-50.png
keywords:
  - ccd
  - core-case-data
  - cdm
  - case-data-management