dependencies:
  - name: postgresql
    version: ~3.1.0
    repository: '@stable'
    tags:
      - postgresql-pod
  - name: idam-pr
    version: ~2.1.0
    repository: '@hmctspublic'
    tags:
      - ccd-idam-pr
  - name: draft-store-service
    version: ~1.0.4
    repository: '@hmctspublic'
  - name: rpe-service-auth-provider
    version: ~0.1.1
    repository: '@hmctspublic'
  - name: payment-api
    version: ~0.0.4
    repository: '@hmctspublic'  

