dependencies:
  - name: postgresql
    version: ~7.0.0
    repository: '@stable'
    tags:
      - postgresql-pod
  - name: idam-pr
    version: ~2.2.5
    repository: '@hmctspublic'
    tags:
      - ccd-idam-pr

