dependencies:
  - name: postgresql
    version: ~3.1.0
    repository: '@stable'
    tags:
      - postgresql-pod
  - name: idam-pr
    version: ~2.0.0
    repository: '@hmcts'
    tags:
      - ccd-idam-pr

