dependencies:
  - name: postgresql
    version: ~6.3.5
    repository: '@stable'
    condition: ccd-postgresql.enabled

  - name: rpe-service-auth-provider
    version: ~0.2.3
    repository: '@hmctspublic'
    condition: rpe-service-auth-provider.enabled

  - name: ccd-user-profile-api
    version: ~1.0.0
    repository: '@hmctspublic'

  - name: ccd-definition-store-api
    version: ~1.0.0
    repository: '@hmctspublic'

  - name: ccd-data-store-api
    version: ~1.1.1
    repository: '@hmctspublic'

  - name: ccd-api-gateway-web
    version: ~1.0.0
    repository: '@hmctspublic'
    condition: ccd-api-gateway-web.enabled

  - name: ccd-admin-web
    version: ~1.0.0
    repository: '@hmctspublic'
    condition: ccd-admin-web.enabled

  - name: ccd-case-management-web
    version: ~1.0.0
    repository: '@hmctspublic'
    condition: ccd-case-management-web.enabled

  - name: draft-store-service
    version: ~1.3.2
    repository: '@hmctspublic'
    condition: draft-store-service.enabled

  - name: dm-store
    version: ~2.0.1
    repository: '@hmctspublic'
    condition: dm-store.enabled

  - name: payment-api
    version: ~0.1.0
    repository: '@hmctspublic'
    condition: payment-api.enabled

  - name: ccd-case-print-service
    version: ~1.0.0
    repository: '@hmctspublic'
    condition: ccd-case-print-service.enabled

  - name: ccd-case-activity-api
    version: ~1.0.0
    repository: '@hmctspublic'
    condition: ccd-case-activity-api.enabled

  - name: ccd-test-stubs-service
    version: ~0.0.4
    repository: '@hmctspublic'
    condition: ccd-test-stubs-service.enabled
  
  
