dependencies:
  - name: postgresql
    version: ~3.1.0
    repository: '@stable'
    tags:
      - postgresql-pod
  - name: idam-pr
    alias: case-mgmt-web-idam-pr
    version: ~1.0.0
#    repository: '@hmcts'
    repository: file:///Users/markry/workspace/hmcts/chart-idam-pr/idam-pr
    tags:
      - case-mgmt-web-idam-pr
  - name: idam-pr
    alias: admin-web-idam-pr
    version: ~1.0.0
#    repository: '@hmcts'
    repository: file:///Users/markry/workspace/hmcts/chart-idam-pr/idam-pr
    tags:
      - admin-web-idam-pr

