dependencies:
  - name: postgresql
    version: 8.9.8
    repository: https://charts.bitnami.com/bitnami
    condition: ccd.postgresql.enabled

  - name: rpe-service-auth-provider
    version: 0.3.21
    repository: '@hmctspublic'
    condition: ccd.s2s.enabled

  - name: ccd-user-profile-api
    version: 1.5.0
    repository: '@hmctspublic'

  - name: ccd-definition-store-api
    version: 1.5.0
    repository: '@hmctspublic'

  - name: ccd-data-store-api
    version: 1.7.0
    repository: '@hmctspublic'

  - name: ccd-api-gateway-web
    version: 1.1.0
    repository: '@hmctspublic'
    condition: ccd.apiGatewayWeb.enabled

  - name: ccd-admin-web
    version: 2.1.0
    repository: '@hmctspublic'
    condition: ccd.adminWeb.enabled

  - name: ccd-case-management-web
    version: 2.1.0
    repository: '@hmctspublic'
    condition: ccd.managementWeb.enabled

  - name: draft-store-service
    version: 2.0.10
    repository: '@hmctspublic'
    condition: ccd.draftStore.enabled

  - name: dm-store
    version: 2.1.3
    repository: '@hmctspublic'
    condition: ccd.dmStore.enabled

  - name: ccpay
    version: 0.1.21-alpha
    repository: '@hmctspublic'
    condition: ccd.ccpay.enabled

  - name: ccd-case-print-service
    version: 1.2.0
    repository: '@hmctspublic'
    condition: ccd.printService.enabled

  - name: ccd-case-activity-api
    version: 1.2.0
    repository: '@hmctspublic'
    condition: ccd.activityApi.enabled

  - name: ccd-test-stubs-service
    version: 1.1.0
    repository: '@hmctspublic'
    condition: ccd.testStubsService.enabled

  - name: ccd-definition-importer
    version: 1.2.3
    repository: '@hmctspublic'
    condition: ccd.definitionImporter.enabled

  - name: ccd-user-profile-importer
    version: ~1.2.2
    repository: '@hmctspublic'
    condition: ccd.userProfileImporter.enabled

  - name: blobstorage
    version: ~0.2.1
    repository: '@hmctspublic'
    condition: ccd.blobstorage.enabled

  - name: em-anno
    version: 1.0.0
    repository: '@hmctspublic'
    condition: ccd.emAnnotation.enabled
