dependencies:
  # - name: postgresql
  #   version: ~5.3.0
  #   repository: '@stable'
  - name: rpe-service-auth-provider
    version: ~0.1.1
    repository: '@hmctspublic'
    tags:
      - rpe-service-auth-provider
  # - name: idam-pr
  #   version: ~2.1.3
  #   repository: '@hmctspublic'
  #   tags:
  #     - ccd-idam-pr
  - name: ccd-user-profile-api
    version: ~1.0.0
    repository: '@hmctspublic'
  - name: ccd-definition-store-api
    version: ~1.0.0
    repository: '@hmctspublic'
  - name: ccd-data-store-api
    version: ~1.1.1
    repository: '@hmctspublic'
  - name: ccd-api-gateway-web
    version: ~1.0.0
    repository: '@hmctspublic'
    condition: ccd-api-gateway-web.enabled
  - name: ccd-admin-web
    version: ~1.0.0
    repository: '@hmctspublic'
    condition: ccd-admin-web.enabled
    tags:
      - front-end-admin
  - name: ccd-case-management-web
    version: ~1.0.0
    repository: '@hmctspublic'
    condition: ccd-case-management-web.enabled
    tags:
      - front-end-management
  - name: ccd-test-stubs-service
    version: ~0.0.4
    repository: '@hmctspublic'
    condition: ccd-test-stubs-service.enabled
    tags:
      - idam-stub
  
