dependencies:
  - name: rpe-service-auth-provider
    version: ~0.1.1
    repository: '@hmctspublic'
  # - name: dm-store
  #   version: ~1.0.1
  #   repository: '@hmctspublic'
  # - name: idam-pr
  #   version: ~2.1.3
  #   repository: '@hmctspublic'
  #   tags:
  #     - ccd-idam-pr
  - name: ccd-user-profile-api
    version: ~1.0.0
    repository: '@hmctspublic'
  # - name: ccd-definition-store-api
  #   version: ~1.0.0
  #   repository: 'hmctspublic'
  # - name: ccd-data-store-api
  #   version: ~1.0.0
  #   repository: 'hmctspublic'
  # - name: ccd-api-gateway
  #   version: ~1.0.0
  #   repository: 'hmctspublic'
  #   tags:
  #     - ccd-api-gw 
  # - name: ccd-case-management-web
  #   version: ~1.0.0
  #   repository: 'hmctspublic'
  #   tags:
  #     - ccd-case-mgmt-web 
