dependencies:
  - name: postgresql
    version: ~6.3.5
    repository: '@stable'
    tags:
      - postgresql-pod
  - name: idam-pr
    version: ~2.2.5
    repository: '@hmctspublic'
    tags:
      - ccd-idam-pr

