---
# TODO only enable if flag set
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api-gateway
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-api-gateway
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: {{ .Values.apiGateway.applicationPort }}
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-api-gateway
