---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-definition-store-api
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-definition-store-api
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: {{ .Values.definitionStoreApi.applicationPort }}
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-definition-store-api
