{{- if and (.Values.consulIP ) (.Values.ingressIP) -}}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-dns"
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-dns
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-dns"
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-dns
    spec:
      volumes:
        - name: container-init
          configMap:
            name: {{ .Release.Name }}-bin
            defaultMode: 0755
      containers:
        - name: {{ .Release.Name }}-dns
          image: hmcts/curl
          volumeMounts:
            - name: container-init
              mountPath: /container.init
          command: [ "/bin/sh" ]
          args:
            - /container.init/ccd-dns
            {{- if .Values.adminWeb.enabled }}
            - admin-web-{{ .Release.Name }}
            {{- end }}          
            {{- if .Values.caseManagementWeb.enabled }}
            - case-management-web-{{ .Release.Name }}
            - gateway-{{ .Release.Name }}
            {{- end }}
            {{- if .Values.printApi.enabled }}
            - print-api-{{ .Release.Name }}
            {{- end }}
            - user-profile-api-{{ .Release.Name }}
            - data-store-api-{{ .Release.Name }}
            - definition-store-api-{{ .Release.Name }}
          resources:
            requests:
              memory: {{ .Values.memoryRequests }}
              cpu: {{ .Values.cpuRequests }}
            limits:
              memory: {{ .Values.memoryLimits }}
              cpu: {{ .Values.cpuLimits }}
      restartPolicy: Never
{{- end -}}